
package principal;

import gestionBD.GestionBD;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author rls
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
    
       initComponents();
       //------------------------------------  cliente
       jPtabla1.setVisible(false);
       jptabla1.setVisible(false);
       txtrutcli.setEnabled(false);
       txtnombrecli.setEnabled(false);
       txtapellidocli.setEnabled(false);
       txtdireccioncli.setEnabled(false);
       txttelefonocli.setEnabled(false);
       txtcorreocli.setEnabled(false);
       btnguardacambio.setVisible(false);
       btnverificacli.setVisible(false);
       btnborrarcli.setVisible(false);
        jtableautos.setVisible(false);
       //---------------------------------------  vehiculo
        txtpatente.setEnabled(false);
        txtmarca.setEnabled(false);
        txtmodelo.setEnabled(false);
        txtcolor.setEnabled(false);
        txtano.setEnabled(false);
        txtvalorarriendo.setEnabled(false);
        comboestado.setEnabled(false);
        check_sedan.setEnabled(false);
        check_jeep.setEnabled(false);
        check_camioneta.setEnabled(false);
        btverificavehiculo.setVisible(false);
        btnborravehiculo.setVisible(false);
        btnguardacambiosauto.setVisible(false);
       
       this.setLocationRelativeTo(null); //centrar formulario
       this.setTitle("byRLS");
    GestionBD rl = new GestionBD();
    
    rl.crearBD();
    rl.crearTablaDEVOLUCION();
    rl.crearTablaCategoriaVehiculo();
    rl.crearTablaCliente();
    rl.crearTablaVehiculo();
    rl.crearTablaContrato();
    
    rl.insertDatoCategoria();
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GRUPO_RADIOBOTON = new javax.swing.ButtonGroup();
        GRUPO_CHECKBOX = new javax.swing.ButtonGroup();
        jTab1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnmostrartablacli = new javax.swing.JButton();
        rbingreso = new javax.swing.JRadioButton();
        rbeliminar = new javax.swing.JRadioButton();
        rbmodificar = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtrutcli = new javax.swing.JTextField();
        txtnombrecli = new javax.swing.JTextField();
        txtapellidocli = new javax.swing.JTextField();
        txtdireccioncli = new javax.swing.JTextField();
        txttelefonocli = new javax.swing.JTextField();
        txtcorreocli = new javax.swing.JTextField();
        btnlimpiarcli = new javax.swing.JButton();
        btnaceptarcli = new javax.swing.JButton();
        btnguardacambio = new javax.swing.JButton();
        btnverificacli = new javax.swing.JButton();
        btnborrarcli = new javax.swing.JButton();
        jptabla1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtablecliente = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtmarca = new javax.swing.JTextField();
        txtmodelo = new javax.swing.JTextField();
        txtcolor = new javax.swing.JTextField();
        txtpatente = new javax.swing.JTextField();
        txtano = new javax.swing.JTextField();
        txtvalorarriendo = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        comboestado = new javax.swing.JComboBox<>();
        check_sedan = new javax.swing.JCheckBox();
        check_jeep = new javax.swing.JCheckBox();
        check_camioneta = new javax.swing.JCheckBox();
        btnlimpiarauto = new javax.swing.JButton();
        btnguardaauto = new javax.swing.JButton();
        btverificavehiculo = new javax.swing.JButton();
        btnborravehiculo = new javax.swing.JButton();
        btnguardacambiosauto = new javax.swing.JButton();
        jPtabla1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtableautos = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        btnmostrartablauto = new javax.swing.JButton();
        rbingresoauto = new javax.swing.JRadioButton();
        rbmodificarauto = new javax.swing.JRadioButton();
        rbeliminarauto = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));

        jPanel10.setBackground(new java.awt.Color(153, 153, 153));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/coche.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/servidor.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/transporte.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel15.setText("      ARRENDAR VEHICULO");

        jLabel16.setText("       DEVOLUCION VEHICULO");

        jLabel17.setText("             CONSULTAS");

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/usuario.png"))); // NOI18N

        jLabel18.setText("Usuarios");

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/car-splash.png"))); // NOI18N

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(210, 210, 210))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jLabel19)
                        .addContainerGap(168, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(187, 187, 187))))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(211, 211, 211)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)))
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTab1.addTab("CONTRATOS", jPanel1);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));

        btnmostrartablacli.setText("Mostrar");
        btnmostrartablacli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmostrartablacliActionPerformed(evt);
            }
        });

        GRUPO_RADIOBOTON.add(rbingreso);
        rbingreso.setText("INGRESAR");
        rbingreso.setToolTipText("");
        rbingreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbingresoActionPerformed(evt);
            }
        });

        GRUPO_RADIOBOTON.add(rbeliminar);
        rbeliminar.setText("ELIMINAR");
        rbeliminar.setToolTipText("");
        rbeliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbeliminarActionPerformed(evt);
            }
        });

        GRUPO_RADIOBOTON.add(rbmodificar);
        rbmodificar.setText("MODIFICAR");
        rbmodificar.setToolTipText("");
        rbmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbmodificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(rbingreso, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rbeliminar, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(rbmodificar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnmostrartablacli)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(rbingreso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbmodificar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbeliminar)
                .addGap(18, 18, 18)
                .addComponent(btnmostrartablacli)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingreso datos de cliente"));

        jLabel1.setText("RUT");

        jLabel2.setText("NOMBRE");

        jLabel3.setText("APELLIDO");

        jLabel4.setText("DIRECCION");

        jLabel5.setText("TELEFONO");

        jLabel6.setText("CORREO");

        btnlimpiarcli.setText("LIMPIAR");
        btnlimpiarcli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarcliActionPerformed(evt);
            }
        });

        btnaceptarcli.setText("GUARDAR");
        btnaceptarcli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaceptarcliActionPerformed(evt);
            }
        });

        btnguardacambio.setText("Guardar Cambios");
        btnguardacambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardacambioActionPerformed(evt);
            }
        });

        btnverificacli.setText("Verificar");
        btnverificacli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnverificacliActionPerformed(evt);
            }
        });

        btnborrarcli.setText("BORRAR");
        btnborrarcli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnborrarcliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnlimpiarcli)
                        .addGap(104, 104, 104)
                        .addComponent(btnaceptarcli)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addComponent(btnguardacambio)
                        .addContainerGap())
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtapellidocli, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtdireccioncli, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnombrecli, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtrutcli, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txttelefonocli, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcorreocli, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnverificacli)
                            .addComponent(btnborrarcli))
                        .addGap(22, 22, 22))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtrutcli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnverificacli))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtnombrecli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnborrarcli))
                .addGap(9, 9, 9)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtapellidocli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtdireccioncli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txttelefonocli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtcorreocli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnlimpiarcli)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnaceptarcli)
                        .addComponent(btnguardacambio)))
                .addContainerGap())
        );

        jptabla1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jtablecliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "RUT", "NOMBRE", "APELLIDO", "DIRECCION", "TELEFONO", "CORREO"
            }
        ));
        jScrollPane1.setViewportView(jtablecliente);

        javax.swing.GroupLayout jptabla1Layout = new javax.swing.GroupLayout(jptabla1);
        jptabla1.setLayout(jptabla1Layout);
        jptabla1Layout.setHorizontalGroup(
            jptabla1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jptabla1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE)
                .addContainerGap())
        );
        jptabla1Layout.setVerticalGroup(
            jptabla1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jptabla1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(301, 301, 301))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jptabla1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(38, 38, 38))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jptabla1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(153, Short.MAX_VALUE))
        );

        jTab1.addTab("CLIENTES", jPanel2);

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingreso vehiculos"));

        jLabel7.setText("CATEGORIA DEL VEHICULO");

        jLabel8.setText("P.P.U.");

        jLabel9.setText("MARCA");

        jLabel10.setText("MODELO");

        jLabel11.setText("COLOR");

        jLabel12.setText("AÑO");

        jLabel13.setText("VALOR ARRIENDO");

        jLabel14.setText("ESTADO");

        comboestado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LIBRE", "ARRENDADO" }));
        comboestado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboestadoActionPerformed(evt);
            }
        });

        GRUPO_CHECKBOX.add(check_sedan);
        check_sedan.setText("SEDAN");

        GRUPO_CHECKBOX.add(check_jeep);
        check_jeep.setText("JEEP");

        GRUPO_CHECKBOX.add(check_camioneta);
        check_camioneta.setText("CAMIONETA");

        btnlimpiarauto.setText("LIMPIAR");
        btnlimpiarauto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarautoActionPerformed(evt);
            }
        });

        btnguardaauto.setText("GUARDAR");
        btnguardaauto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardaautoActionPerformed(evt);
            }
        });

        btverificavehiculo.setText("Verifica");
        btverificavehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btverificavehiculoActionPerformed(evt);
            }
        });

        btnborravehiculo.setText("Borrar");
        btnborravehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnborravehiculoActionPerformed(evt);
            }
        });

        btnguardacambiosauto.setText("GUARDAR CAMBIOS");
        btnguardacambiosauto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardacambiosautoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14))
                                .addGap(56, 56, 56)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtpatente)
                                    .addComponent(txtano)
                                    .addComponent(txtmarca, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtcolor)
                                    .addComponent(txtvalorarriendo, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtmodelo, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(comboestado, 0, 237, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btverificavehiculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnborravehiculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(check_sedan)
                                .addGap(18, 18, 18)
                                .addComponent(check_jeep)
                                .addGap(18, 18, 18)
                                .addComponent(check_camioneta)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnlimpiarauto)
                        .addGap(76, 76, 76)
                        .addComponent(btnguardaauto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnguardacambiosauto)
                        .addGap(3, 3, 3))))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtpatente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btverificavehiculo))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtmarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(txtmodelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnborravehiculo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcolor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtvalorarriendo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(comboestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(check_sedan)
                    .addComponent(check_jeep)
                    .addComponent(check_camioneta))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnguardaauto)
                    .addComponent(btnlimpiarauto)
                    .addComponent(btnguardacambiosauto))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPtabla1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jtableautos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "P.P.U.", "MARCA", "MODELO", "COLOR", "AÑO", "VALOR_ARRIENDO", "ESTADO", "CATEGORIA"
            }
        ));
        jScrollPane2.setViewportView(jtableautos);

        javax.swing.GroupLayout jPtabla1Layout = new javax.swing.GroupLayout(jPtabla1);
        jPtabla1.setLayout(jPtabla1Layout);
        jPtabla1Layout.setHorizontalGroup(
            jPtabla1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPtabla1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPtabla1Layout.setVerticalGroup(
            jPtabla1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPtabla1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));

        btnmostrartablauto.setText("Mostrar");
        btnmostrartablauto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmostrartablautoActionPerformed(evt);
            }
        });

        GRUPO_RADIOBOTON.add(rbingresoauto);
        rbingresoauto.setText("INGRESAR");
        rbingresoauto.setToolTipText("");
        rbingresoauto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbingresoautoActionPerformed(evt);
            }
        });

        GRUPO_RADIOBOTON.add(rbmodificarauto);
        rbmodificarauto.setText("MODIFICAR");
        rbmodificarauto.setToolTipText("");
        rbmodificarauto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbmodificarautoActionPerformed(evt);
            }
        });

        GRUPO_RADIOBOTON.add(rbeliminarauto);
        rbeliminarauto.setText("ELIMINAR");
        rbeliminarauto.setToolTipText("");
        rbeliminarauto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbeliminarautoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbeliminarauto)
                    .addComponent(rbmodificarauto)
                    .addComponent(rbingresoauto, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnmostrartablauto)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(rbingresoauto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbmodificarauto, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbeliminarauto, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnmostrartablauto)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPtabla1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPtabla1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(371, 371, 371))
        );

        jTab1.addTab("VEHICULOS", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTab1, javax.swing.GroupLayout.PREFERRED_SIZE, 756, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTab1, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnmostrartablacliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmostrartablacliActionPerformed
        // TODO add your handling code here:
          GestionBD rl = new GestionBD();
          jPtabla1.setVisible(true);
        jptabla1.setVisible(true);
        jtablecliente.setVisible(true);
        
        rl.mostraDatoCliente(jtablecliente);
        
        
        
    }//GEN-LAST:event_btnmostrartablacliActionPerformed

    private void comboestadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboestadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboestadoActionPerformed

    private void btnmostrartablautoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmostrartablautoActionPerformed
        // TODO add your handling code here:
         GestionBD rl = new GestionBD();
         jPtabla1.setVisible(true);
         jtableautos.setVisible(true);
         rl.mostraDatoVehiculo(jtableautos);
    }//GEN-LAST:event_btnmostrartablautoActionPerformed

    private void btnaceptarcliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaceptarcliActionPerformed
        // TODO add your handling code here:
        String rut    = txtrutcli.getText();
        String nombre = txtnombrecli.getText();
        String apellido = txtapellidocli.getText();
        String direccion = txtdireccioncli.getText();
        int    telefono = Integer.parseInt(txttelefonocli.getText());
        String correo = txtcorreocli.getText();
        
         GestionBD rl = new GestionBD();
         
      /*  if (txtrutcli.getText() != null){           
            if (txtnombrecli.getText() != null){
                if (txtapellidocli.getText()!= null){
                    if(txtdireccioncli.getText()!= null){
                        if(txttelefonocli.getText() != null){
                            if(txtcorreocli.getText()!= null){
                            
                            }
                        }
                    }
                }
            }
        }
        
        */
      try{
      rl.insertDatoCliente(rut, nombre, apellido, direccion, telefono, correo);
        
      }catch (Exception e){
      JOptionPane.showMessageDialog(null,"Error casilla en blanco"+ e);
      }  
      txtrutcli.setText("");
      txtnombrecli.setText("");
      txtapellidocli.setText("");
      txtdireccioncli.setText("");
      txttelefonocli.setText("");
      txtcorreocli.setText("");
      
      
    }//GEN-LAST:event_btnaceptarcliActionPerformed

    private void rbingresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbingresoActionPerformed

        // TODO add your handling code here:

      txtrutcli.setText("");
      txtnombrecli.setText("");
      txtapellidocli.setText("");
      txtdireccioncli.setText("");
      txttelefonocli.setText("");
      txtcorreocli.setText("");

        btnaceptarcli.setVisible(true);
        btnlimpiarcli.setVisible(true);
    
       txtrutcli.setEnabled(true);
       txtnombrecli.setEnabled(true);
       txtapellidocli.setEnabled(true);
       txtdireccioncli.setEnabled(true);
       txttelefonocli.setEnabled(true);
        txtcorreocli.setEnabled(true);
        btnverificacli.setVisible(false);
        btnguardacambio.setVisible(false);
        btnborrarcli.setVisible(false);
    }//GEN-LAST:event_rbingresoActionPerformed

    private void rbmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbmodificarActionPerformed
        // TODO add your handling code here:
        txtrutcli.setEnabled(true);
       txtnombrecli.setEnabled(false);
       txtapellidocli.setEnabled(false);
       txtdireccioncli.setEnabled(false);
       txttelefonocli.setEnabled(false);
        txtcorreocli.setEnabled(false);
        btnguardacambio.setVisible(true);
        btnverificacli.setVisible(true);
        btnaceptarcli.setVisible(false);
        btnlimpiarcli.setVisible(false);
      
        btnborrarcli.setVisible(false);
        


    }//GEN-LAST:event_rbmodificarActionPerformed

    private void rbeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbeliminarActionPerformed
        // TODO add your handling code here:
       txtrutcli.setText("");
      txtnombrecli.setText("");
      txtapellidocli.setText("");
      txtdireccioncli.setText("");
      txttelefonocli.setText("");
      txtcorreocli.setText("");

        btnlimpiarcli.setVisible(false);
       btnaceptarcli.setVisible(false);
        txtrutcli.setEnabled(true);
       txtnombrecli.setEnabled(false);
       txtapellidocli.setEnabled(false);
       txtdireccioncli.setEnabled(false);
       txttelefonocli.setEnabled(false);
       txtcorreocli.setEnabled(false);
       btnborrarcli.setVisible(true);
       btnguardacambio.setVisible(false);
       btnverificacli.setVisible(true);



    }//GEN-LAST:event_rbeliminarActionPerformed

    private void btnguardacambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardacambioActionPerformed
        // TODO add your handling code here:
        
           //buscarlo en la base de datos luego activa y muestra
        
         txtnombrecli.setEnabled(true);
       txtapellidocli.setEnabled(true);
       txtdireccioncli.setEnabled(true);
       txttelefonocli.setEnabled(true);
        txtcorreocli.setEnabled(true);

        GestionBD rl = new GestionBD();
        
        String RUT = txtrutcli.getText();
        String NOMBRE = txtnombrecli.getText();
        String APELLIDO = txtapellidocli.getText();
        String DIRECCION = txtdireccioncli.getText();
        String TELEFONO = txttelefonocli.getText();
        String CORREO = txtcorreocli.getText();
        
                rl.modificarDatoCliente(NOMBRE,APELLIDO,DIRECCION,TELEFONO,CORREO, RUT);
        
     

    }//GEN-LAST:event_btnguardacambioActionPerformed

    private void btnverificacliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnverificacliActionPerformed
        // TODO add your handling code here:
        GestionBD rl = new GestionBD();
        String RU = txtrutcli.getText();
       txtnombrecli.setEnabled(true);
       txtapellidocli.setEnabled(true);
       txtdireccioncli.setEnabled(true);
       txttelefonocli.setEnabled(true);
        txtcorreocli.setEnabled(true);
        rl.mostraDatoClienteunico( txtnombrecli,txtapellidocli,txtdireccioncli,txttelefonocli,txtcorreocli, RU);

       

    }//GEN-LAST:event_btnverificacliActionPerformed

    private void btnborrarcliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnborrarcliActionPerformed
        // TODO add your handling code here:
        GestionBD rl = new GestionBD();
        String brr = txtrutcli.getText();
        JOptionPane.showMessageDialog(null,"Ud. se encuentra borrando el Cliente : "+brr);
        rl.eliminarDatoCliente(brr);
        rl.mostraDatoCliente(jtablecliente);
      txtrutcli.setText("");
      txtnombrecli.setText("");
      txtapellidocli.setText("");
      txtdireccioncli.setText("");
      txttelefonocli.setText("");
      txtcorreocli.setText("");

    }//GEN-LAST:event_btnborrarcliActionPerformed

    private void btnlimpiarcliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarcliActionPerformed
        // TODO add your handling code here:
     txtrutcli.setText("");
      txtnombrecli.setText("");
      txtapellidocli.setText("");
      txtdireccioncli.setText("");
      txttelefonocli.setText("");
      txtcorreocli.setText("");

    }//GEN-LAST:event_btnlimpiarcliActionPerformed

    private void btnguardaautoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardaautoActionPerformed
        // TODO add your handling code here:
        GestionBD rl = new GestionBD();
       /* txtpatente.setText("");
        txtmarca.setText("");
        txtmodelo.setText("");
        txtcolor.setText("");
        txtano.setText("");
        txtvalorarriendo.setText("");
        */
        String PPU = txtpatente.getText();
        String MARCA =txtmarca.getText();
        String MODELO=txtmodelo.getText();
        String COLOR =txtcolor.getText();
        String AÑO =txtano.getText();
        int VALORDIA = Integer.parseInt( txtvalorarriendo.getText());
        String ESTADO = (String)comboestado.getSelectedItem();//COMBO BOX ESTADO SELECCION
                                            //SELECCIONAR CATEGORIA DEL CHECKBOX
        String ID_CAT = "100";                                   
       if(check_sedan.isSelected() ){
            ID_CAT = "100";
        }
           if(check_jeep.isSelected() ){
            ID_CAT = "200";
        }
           if(check_camioneta.isSelected() ){
            ID_CAT = "300";
           }
        rl.insertDatoVehiculo(PPU,MARCA,MODELO,COLOR,AÑO,VALORDIA,ESTADO,ID_CAT);
           
           
           

    }//GEN-LAST:event_btnguardaautoActionPerformed

    private void btnlimpiarautoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarautoActionPerformed
        // TODO add your handling code here:

        txtpatente.setText("");
        txtmarca.setText("");
        txtmodelo.setText("");
        txtcolor.setText("");
        txtano.setText("");
        txtvalorarriendo.setText("");
        
        check_sedan.setEnabled(true);
        check_jeep.setEnabled(true);
        check_camioneta.setEnabled(true);


    }//GEN-LAST:event_btnlimpiarautoActionPerformed

    private void rbmodificarautoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbmodificarautoActionPerformed
        // TODO add your handling code here:
        txtpatente.setEnabled(true);
        txtmarca.setEnabled(false);
        txtmodelo.setEnabled(false);
        txtcolor.setEnabled(false);
        txtano.setEnabled(false);
        txtvalorarriendo.setEnabled(false);
        comboestado.setEnabled(false);
        check_sedan.setEnabled(false);
        check_jeep.setEnabled(false);
        check_camioneta.setEnabled(false);
        btverificavehiculo.setVisible(true);
        btnborravehiculo.setVisible(false);
        btnguardaauto.setVisible(false);
        btnguardacambiosauto.setVisible(true);


    }//GEN-LAST:event_rbmodificarautoActionPerformed

    private void rbingresoautoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbingresoautoActionPerformed
        // TODO add your handling code here:
        txtpatente.setEnabled(true);
        txtmarca.setEnabled(true);
        txtmodelo.setEnabled(true);
        txtcolor.setEnabled(true);
        txtano.setEnabled(true);
        txtvalorarriendo.setEnabled(true);
        comboestado.setEnabled(true);
        check_sedan.setEnabled(true);
        check_jeep.setEnabled(true);
        check_camioneta.setEnabled(true);
        btverificavehiculo.setVisible(false);
        btnborravehiculo.setVisible(false);
        btnguardaauto.setVisible(true);

    }//GEN-LAST:event_rbingresoautoActionPerformed

    private void rbeliminarautoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbeliminarautoActionPerformed
        // TODO add your handling code here:
        txtpatente.setEnabled(true);
        txtmarca.setEnabled(false);
        txtmodelo.setEnabled(false);
        txtcolor.setEnabled(false);
        txtano.setEnabled(false);
        txtvalorarriendo.setEnabled(false);
        comboestado.setEnabled(false);
        check_sedan.setEnabled(false);
        check_jeep.setEnabled(false);
        check_camioneta.setEnabled(false);
        btnborravehiculo.setVisible(true);
        btnguardaauto.setVisible(false);
        btnlimpiarauto.setVisible(false);
        btverificavehiculo.setVisible(true);

    }//GEN-LAST:event_rbeliminarautoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Arriendo arriendo = new Arriendo();
        arriendo.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Devolucion devolucion = new Devolucion();
        devolucion.setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        consultas con   = new consultas();
        con.setVisible(true);
        dispose();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnguardacambiosautoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardacambiosautoActionPerformed
        // TODO add your handling code here:
          GestionBD rl = new GestionBD();
          String PPU=txtpatente.getText();
          String MARCA=txtmarca.getText();
          String MODELO=txtmodelo.getText();
          String COLOR=txtcolor.getText();
          String AÑO=txtano.getText();
          int VALORDIA= Integer.parseInt(txtvalorarriendo.getText());
          String ESTADO=(String)comboestado.getSelectedItem();
          
          String ID_CAT ="100";
            if(check_sedan.isSelected() ){
            ID_CAT = "100";
        }
           if(check_jeep.isSelected() ){
            ID_CAT = "200";
        }
           if(check_camioneta.isSelected() ){
            ID_CAT = "300";
           }
                  
                  
          rl.modificarDatoVehiculo(PPU, MARCA, MODELO, COLOR, AÑO, VALORDIA, ESTADO, ID_CAT);

    }//GEN-LAST:event_btnguardacambiosautoActionPerformed

    private void btverificavehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btverificavehiculoActionPerformed
        // TODO add your handling code here:
        GestionBD rl = new GestionBD();

        String PPU = txtpatente.getText();
       txtmarca.setEnabled(true);
       txtmodelo.setEnabled(true);
       txtcolor.setEnabled(true);
       txtano.setEnabled(true);
       txtvalorarriendo.setEnabled(true);
       comboestado.setEnabled(true);
        check_sedan.setEnabled(true);
       check_jeep.setEnabled(true);
        check_camioneta.setEnabled(true);
        rl.mostraDatoVehiculoUnico(txtmarca, txtmodelo, txtcolor, txtano, txtvalorarriendo,comboestado, PPU);

       


    }//GEN-LAST:event_btverificavehiculoActionPerformed

    private void btnborravehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnborravehiculoActionPerformed
        // TODO add your handling code here:
     
        
        GestionBD rl = new GestionBD();
            String PPU=txtpatente.getText();
            rl.eliminarDatoVehiculo(PPU);
            rl.mostraDatoVehiculo(jtableautos);

        txtpatente.setText("");
        txtmarca.setText("");
        txtmodelo.setText("");
        txtcolor.setText("");
        txtano.setText("");
        txtvalorarriendo.setText("");  
            
            
            
    }//GEN-LAST:event_btnborravehiculoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GRUPO_CHECKBOX;
    private javax.swing.ButtonGroup GRUPO_RADIOBOTON;
    private javax.swing.JButton btnaceptarcli;
    private javax.swing.JButton btnborrarcli;
    private javax.swing.JButton btnborravehiculo;
    private javax.swing.JButton btnguardaauto;
    private javax.swing.JButton btnguardacambio;
    private javax.swing.JButton btnguardacambiosauto;
    private javax.swing.JButton btnlimpiarauto;
    private javax.swing.JButton btnlimpiarcli;
    private javax.swing.JButton btnmostrartablacli;
    private javax.swing.JButton btnmostrartablauto;
    private javax.swing.JButton btnverificacli;
    private javax.swing.JButton btverificavehiculo;
    private javax.swing.JCheckBox check_camioneta;
    private javax.swing.JCheckBox check_jeep;
    private javax.swing.JCheckBox check_sedan;
    private javax.swing.JComboBox<String> comboestado;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPtabla1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTab1;
    private javax.swing.JPanel jptabla1;
    private javax.swing.JTable jtableautos;
    private javax.swing.JTable jtablecliente;
    private javax.swing.JRadioButton rbeliminar;
    private javax.swing.JRadioButton rbeliminarauto;
    private javax.swing.JRadioButton rbingreso;
    private javax.swing.JRadioButton rbingresoauto;
    private javax.swing.JRadioButton rbmodificar;
    private javax.swing.JRadioButton rbmodificarauto;
    private javax.swing.JTextField txtano;
    private javax.swing.JTextField txtapellidocli;
    private javax.swing.JTextField txtcolor;
    private javax.swing.JTextField txtcorreocli;
    private javax.swing.JTextField txtdireccioncli;
    private javax.swing.JTextField txtmarca;
    private javax.swing.JTextField txtmodelo;
    private javax.swing.JTextField txtnombrecli;
    private javax.swing.JTextField txtpatente;
    private javax.swing.JTextField txtrutcli;
    private javax.swing.JTextField txttelefonocli;
    private javax.swing.JTextField txtvalorarriendo;
    // End of variables declaration//GEN-END:variables
}
